version: '3.8'

services:
  php:
    build: .
    container_name: lab9_php
    volumes:
      - ./code/:/var/www/html
      - ./tests/:/var/www/html/tests
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-test_db}
      - DB_USER=${DB_USER:-test_user}
      - DB_PASSWORD=${DB_PASSWORD:-test_pass}
    depends_on:
      - db
    env_file:
      - .env.test

  db:
    image: mysql:8.0
    container_name: lab9_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DB_NAME:-test_db}
      MYSQL_USER: ${DB_USER:-test_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-test_pass}
    ports:
      - "3307:3306"